BUILD_DATE := $(shell date +%Y%m%d)
BUILD_TIME := $(shell date +%H%M)

ifeq ($(TARGET_BUILD_GAPPS),false)
    WYPIERDALAJ_VARIANT := VANILLA
else
    WYPIERDALAJ_VARIANT := GAPPS
endif

WYPIERDALAJ_BUILD_TYPE ?= UNOFFICIAL

# Set all versions
WYPIERDALAJ_PLATFORM_VERSION := 12.1
TARGET_PRODUCT_SHORT := $(subst wypierdalaj_,,$(TARGET_PRODUCT))
WYPIERDALAJ_VERSION := Wypierdalaj-$(WYPIERDALAJ_PLATFORM_VERSION)-$(WYPIERDALAJ_BUILD_TYPE)-$(WYPIERDALAJ_VARIANT)-$(TARGET_PRODUCT_SHORT)-$(BUILD_DATE)-$(BUILD_TIME)
ROM_FINGERPRINT := Wypierdalaj/$(PLATFORM_VERSION)/$(WYPIERDALAJ_BUILD_TYPE)/$(BUILD_DATE)$(BUILD_TIME)

# Declare it's a WypierdalajOS build
WYPIERDALAJ_BUILD := true
